NiceAdmin/Controllers/BillController.cs
using Microsoft.AspNetCore.Mvc;
using NiceAdmin.Models;
using System.Data.SqlClient;
using System.Data;
using System.Collections.Specialized;
using OfficeOpenXml;
using System.Drawing;

namespace NiceAdmin.Controllers
{
    public class BillController : Controller
    {
        private IConfiguration configuration;

        public BillController(IConfiguration _configuration)
        {
            configuration = _configuration;
        }

        #region BillList
        public IActionResult Bills()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            SqlConnection sqlConnection = new SqlConnection(connectionString);
            sqlConnection.Open();
            SqlCommand sqlCommand = sqlConnection.CreateCommand();
            sqlCommand.CommandType = CommandType.StoredProcedure;
            sqlCommand.CommandText = "PR_Bills_SelectAll";
            SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();
            DataTable dataTable = new DataTable();
            dataTable.Load(sqlDataReader);
            return View(dataTable);
        }
        #endregion

        #region BillDelete
        public IActionResult BillDelete(int BillID)
        {
            try
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection sqlConnection = new SqlConnection(connectionString);
                sqlConnection.Open();
                SqlCommand sqlCommand = sqlConnection.CreateCommand();
                sqlCommand.CommandType = CommandType.StoredProcedure;
                sqlCommand.CommandText = "PR_Bills_DeleteByPK";
                sqlCommand.Parameters.Add("@BillID", SqlDbType.Int).Value = BillID;
                sqlCommand.ExecuteNonQuery();
                return RedirectToAction("Bills");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString);
                return RedirectToAction("Bills");
            }
        }
        #endregion

        #region BillSave
        public IActionResult BillSave(BillModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = this.configuration.GetConnectionString("ConnectionString");
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                if (model.BillID == 0)
                {
                    command.CommandText = "PR_Bills_Insert";
                }
                else
                {
                    command.CommandText = "PR_Bills_UpdateByPK";
                    command.Parameters.Add("@BillID", SqlDbType.Int).Value = model.BillID;
                }
                command.Parameters.Add("@BillNumber", SqlDbType.VarChar).Value = model.BillNumber;
                command.Parameters.Add("@BillDate", SqlDbType.Date).Value = model.BillDate;
                command.Parameters.Add("@OrderID", SqlDbType.Int).Value = model.OrderID;
                command.Parameters.Add("@TotalAmount", SqlDbType.Decimal).Value = model.TotalAmount;
                command.Parameters.Add("@Discount", SqlDbType.Decimal).Value = model.Discount;
                command.Parameters.Add("@NetAmount", SqlDbType.Decimal).Value = model.NetAmount;
                command.Parameters.Add("@UserID", SqlDbType.Int).Value = model.UserID;
                command.ExecuteNonQuery();
                TempData["SuccessMessage"] = model.BillID == 0 ? "Bill added successfully!" : "Bill updated successfully!";
                return RedirectToAction("Bills");
            }

            return View("BillsForm", model);
        }
        #endregion

        #region BillForm/Dropdown
        public IActionResult BillsForm(int? BillID)
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");

            SqlConnection sqlConnection1 = new SqlConnection(connectionString);
            sqlConnection1.Open();
            SqlCommand command1 = sqlConnection1.CreateCommand();
            command1.CommandType = System.Data.CommandType.StoredProcedure;
            command1.CommandText = "PR_User_DropDown";
            SqlDataReader reader1 = command1.ExecuteReader();
            DataTable dataTable1 = new DataTable();
            dataTable1.Load(reader1);
            List<UserDropDownModel> userList = new List<UserDropDownModel>();
            foreach (DataRow data in dataTable1.Rows)
            {
                UserDropDownModel userDropDownModel = new UserDropDownModel();
                userDropDownModel.UserID = Convert.ToInt32(data["UserID"]);
                userDropDownModel.UserName = data["UserName"].ToString();
                userList.Add(userDropDownModel);
            }

            ViewBag.Users = userList;

            SqlConnection sqlConnection2 = new SqlConnection(connectionString);
            sqlConnection2.Open();
            SqlCommand command2 = sqlConnection1.CreateCommand();
            command2.CommandType = System.Data.CommandType.StoredProcedure;
            command2.CommandText = "PR_Orders_DropDown";
            SqlDataReader reader2 = command2.ExecuteReader();
            DataTable dataTable2 = new DataTable();
            dataTable2.Load(reader2);
            List<OrderDropDownModel> orderList = new List<OrderDropDownModel>();
            foreach (DataRow data in dataTable2.Rows)
            {
                OrderDropDownModel orderDropDownModel = new OrderDropDownModel();
                orderDropDownModel.OrderID = Convert.ToInt32(data["OrderID"]);
                orderDropDownModel.OrderCode = data["OrderCode"].ToString();
                orderList.Add(orderDropDownModel);
            }

            ViewBag.Orders = orderList;

            BillModel billModel = new BillModel();
            if (BillID.HasValue)
            {
                SqlConnection connection = new SqlConnection(connectionString);
                connection.Open();
                SqlCommand command = connection.CreateCommand();
                command.CommandType = CommandType.StoredProcedure;
                command.CommandText = "PR_Bills_SelectByPK";
                command.Parameters.AddWithValue("@BillID", BillID);
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                foreach (DataRow dataRow in table.Rows)
                {
                    billModel.BillID = Convert.ToInt32(dataRow["OrderID"]);
                    billModel.BillNumber = @dataRow["BillNumber"].ToString();
                    billModel.BillDate = Convert.ToDateTime(@dataRow["BillDate"]);
                    billModel.OrderID = Convert.ToInt32(@dataRow["OrderID"]);
                    billModel.TotalAmount = Convert.ToDecimal(@dataRow["TotalAmount"]);
                    billModel.Discount = Convert.ToDecimal(@dataRow["Discount"]);
                    billModel.NetAmount = Convert.ToDecimal(@dataRow["NetAmount"]);
                    billModel.UserID = Convert.ToInt32(@dataRow["UserID"]);
                }

                ViewData["Title"] = "Edit Bill";
            }
            else
            {
                ViewData["Title"] = "Add Bill";
            }
            return View("BillsForm", billModel);
        }
        #endregion

        #region ExcelCode
        public IActionResult ExportToExcel()
        {
            string connectionString = this.configuration.GetConnectionString("ConnectionString");
            using (var sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                using (var sqlCommand = sqlConnection.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_Bills_SelectAll";
                    using (var sqlDataReader = sqlCommand.ExecuteReader())
                    {
                        var dataTable = new DataTable();
                        dataTable.Load(sqlDataReader);

                        using (var package = new ExcelPackage())
                        {
                            var worksheet = package.Workbook.Worksheets.Add("Users");
                            worksheet.Cells["A1"].LoadFromDataTable(dataTable, true);

                            var stream = new MemoryStream();
                            package.SaveAs(stream);
                            stream.Position = 0;

                            var fileName = "Bills.xlsx";
                            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                        }
                    }
                }
            }
        }
        #endregion
    }
}

NiceAdmin/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;
using System.Data;
using NiceAdmin.Models;
using OfficeOpenXml;

namespace NiceAdmin.Controllers
{
    public class CountryController : Controller
    {
        private readonly IConfiguration _configuration;

        #region configuration
        public CountryController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        #endregion

        #region Index
        public IActionResult Index()
        {
            string connectionstr = this._configuration.GetConnectionString("ConnectionString");
            //PrePare a connection
            DataTable dt = new DataTable();
            SqlConnection conn = new SqlConnection(connectionstr);
            conn.Open();

            //Prepare a Command
            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            objCmd.CommandText = "PR_LOC_Country_SelectAll";

            SqlDataReader objSDR = objCmd.ExecuteReader();
            dt.Load(objSDR);
            conn.Close();
            return View("Index", dt);
        }
        #endregion

        #region CountryDelete
        public IActionResult CountryDelete(int CountryID)
        {
            try
            {
                string connectionString = this._configuration.GetConnectionString("ConnectionString");
                using (SqlConnection sqlConnection = new SqlConnection(connectionString))
                {
                    sqlConnection.Open();
                    using (SqlCommand sqlCommand = sqlConnection.CreateCommand())
                    {
                        sqlCommand.CommandType = CommandType.StoredProcedure;
                        sqlCommand.CommandText = "PR_LOC_Country_Delete";
                        sqlCommand.Parameters.Add("@CountryID", SqlDbType.Int).Value = CountryID;
                        sqlCommand.ExecuteNonQuery();
                    }
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                Console.WriteLine(ex.ToString());
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region ExcelCode
        public IActionResult ExportToExcel()
        {
            string connectionString = this._configuration.GetConnectionString("ConnectionString");
            using (var sqlConnection = new SqlConnection(connectionString))
            {
                sqlConnection.Open();
                using (var sqlCommand = sqlConnection.CreateCommand())
                {
                    sqlCommand.CommandType = CommandType.StoredProcedure;
                    sqlCommand.CommandText = "PR_LOC_Country_SelectAll";

                    using (var sqlDataReader = sqlCommand.ExecuteReader())
                    {
                        var dataTable = new DataTable();
                        dataTable.Load(sqlDataReader);

                        using (var package = new ExcelPackage())
                        {
                            var worksheet = package.Workbook.Worksheets.Add("Countries");
                            worksheet.Cells["A1"].LoadFromDataTable(dataTable, true);
                            var stream = new MemoryStream();
                            package.SaveAs(stream);
                            stream.Position = 0;
                            var fileName = "Countries.xlsx";
                            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                        }
                    }
                }
            }
        }
        #endregion

        #region Add
        // This action displays the Country Add/Edit form
        public IActionResult CountryAddEdit(int? CountryID)
        {
            // Check if an edit operation is requested
            if (CountryID.HasValue)
            {
                string connectionstr = _configuration.GetConnectionString("ConnectionString");
                DataTable dt = new DataTable();

                // Fetch country details by ID
                using (SqlConnection conn = new SqlConnection(connectionstr))
                {
                    conn.Open();
                    using (SqlCommand objCmd = conn.CreateCommand())
                    {
                        objCmd.CommandType = CommandType.StoredProcedure;
                        objCmd.CommandText = "PR_LOC_Country_SelectByPK";
                        objCmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = CountryID;

                        using (SqlDataReader objSDR = objCmd.ExecuteReader())
                        {
                            dt.Load(objSDR); // Load data into DataTable
                        }
                    }
                }

                if (dt.Rows.Count > 0)
                {
                    // Map data to CountryModel
                    CountryModel model = new CountryModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        model.CountryID = Convert.ToInt32(dr["CountryID"]);
                        model.CountryName = dr["CountryName"].ToString();
                        model.CountryCode = dr["CountryCode"].ToString();
                    }
                    return View("CountryAddEdit", model); // Return populated model to view
                }
            }

            return View("CountryAddEdit"); // For adding a new country
        }
        #endregion

        #region Save
        // Save action handles both insert and update operations for Country
        [HttpPost]
        public IActionResult SaveCountry(CountryModel modelCountry)
        {
            if (ModelState.IsValid)
            {
                string connectionstr = _configuration.GetConnectionString("ConnectionString");
                using (SqlConnection conn = new SqlConnection(connectionstr))
                {
                    conn.Open();
                    using (SqlCommand objCmd = conn.CreateCommand())
                    {
                        objCmd.CommandType = CommandType.StoredProcedure;

                        // Choose procedure based on operation (insert or update)
                        if (modelCountry.CountryID == null)
                        {
                            objCmd.CommandText = "pr_LOC_Country_Insert";
                        }
                        else
                        {
                            objCmd.CommandText = "pr_LOC_Country_Update";
                            objCmd.Parameters.Add("@CountryID", SqlDbType.Int).Value = modelCountry.CountryID;
                        }

                        // Pass parameters
                        objCmd.Parameters.Add("@CountryName", SqlDbType.VarChar).Value = modelCountry.CountryName;
                        objCmd.Parameters.Add("@CountryCode", SqlDbType.VarChar).Value = modelCountry.CountryCode;

                        objCmd.ExecuteNonQuery(); // Execute the query
                    }
                }

                TempData["CountryInsertMsg"] = "Record Saved Successfully"; // Success message
                return RedirectToAction("Index"); // Redirect to country listing
            }

            return View("CountryAddEdit", modelCountry);
        }
        #endregion
    }
}

NiceAdmin/Views/Shared/Register.cshtml
@{
    Layout = "~/Views/Shared/_Layout_Register.cshtml";
}

@model NiceAdmin.Models.UserRegisterModel


<main style="background-image: url('https://static.vecteezy.com/system/resources/previews/022/170/308/non_2x/blurred-background-coffee-shop-in-garden-blur-background-with-bokeh-generative-ai-photo.jpeg'); background-size: cover; background-position: center; background-attachment: fixed; background-repeat: no-repeat;">
    <div class="container">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">
                @TempData["ErrorMessage"]
            </div>
        }
        <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                        <div class="d-flex justify-content-center py-4">
                            <a class="logo d-flex align-items-center w-auto" style="text-shadow: 2px 2px 4px rgba(0,0,0,0.7); background: rgba(255,255,255,0.7); padding: 5px; border-radius: 5px;">
                                <img src="https://th.bing.com/th/id/OIP.3l72hn0LshdLgG5RBQD91QAAAA?rs=1&pid=ImgDetMain" alt="Coffee Shop Logo" style="max-height: 100px; width: auto;">
                                <span class="d-none d-lg-block" style="font-size: 1.5rem; font-weight: bold; color: #333;">Coffee Shop</span>
                            </a>
                        </div><!-- End Logo -->

                        <div class="card mb-3">

                            <div class="card-body">

                                <div class="pt-4 pb-2">
                                    <h5 class="card-title text-center pb-0 fs-4">Create an Account</h5>
                                    <p class="text-center small">Enter your personal details to create account</p>
                                </div>

                                <form class="row g-3 needs-validation" asp-controller="User" asp-action="UserRegister" novalidate>
                                    <div class="col-12">
                                        <label for="yourName" class="form-label">UserName</label>
                                        <input type="text" asp-for="UserName" class="form-control" id="yourName">
                                        <span class="text-danger" asp-validation-for="UserName"></span>
                                    </div>

                                    <div class="col-12">
                                        <label for="yourEmail" class="form-label">Password</label>
                                        <input type="password" asp-for="Password" class="form-control" id="yourEmail">
                                        <span class="text-danger" asp-validation-for="Password"></span>
                                    </div>

                                    <div class="col-12">
                                        <label for="yourEmail" class="form-label">Email</label>
                                        <input type="email" asp-for="Email" class="form-control" id="yourEmail">
                                        <span class="text-danger" asp-validation-for="Email"></span>
                                    </div>

                                    <div class="col-12">
                                        <label for="yourEmail" class="form-label">Mobile Number</label>
                                        <input type="number" asp-for="MobileNo" class="form-control" id="yourEmail">
                                        <span class="text-danger" asp-validation-for="MobileNo"></span>
                                    </div>

                                    <div class="col-12">
                                        <label for="yourEmail" class="form-label">Address</label>
                                        <input type="text" asp-for="Address" class="form-control" id="yourEmail">
                                        <span class="text-danger" asp-validation-for="Address"></span>
                                    </div>

                                    <div class="col-12">
                                        <div class="form-check">
                                            <input class="form-check-input" name="terms" type="checkbox" value="" id="acceptTerms" required>
                                            <label class="form-check-label" for="acceptTerms">I agree and accept the <a href="#">terms and conditions</a></label>
                                            <div class="invalid-feedback">You must agree before submitting.</div>
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <button class="btn btn-primary w-100" type="submit">Create Account</button>
                                    </div>
                                    <div class="col-12">
                                        <p class="small mb-0">Already have an account? <a asp-controller="User" asp-action="Login">Log in</a></p>
                                    </div>
                                </form>

                            </div>
                        </div>


                    </div>
                </div>
            </div>

        </section>

    </div>
</main><!-- End #main -->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

NiceAdmin/Views/Shared/_Layout.cshtml
@using NiceAdmin;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Pages / Coffee Shope</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
   <!-- ======= Header ======= -->
            <header id="header" class="header fixed-top d-flex align-items-center">
                <div class="d-flex align-items-center justify-content-between">
                    <a href="@Url.Action("Index", "Home")" class="logo d-flex align-items-center">
                        <img src="https://th.bing.com/th/id/OIP.3l72hn0LshdLgG5RBQD91QAAAA?rs=1&pid=ImgDetMain" alt="Coffee Shop Logo" style="max-height: 50px; width: auto;">
                        <span class="d-none d-lg-block">Coffee Shop</span>
                    </a>
                    <i class="bi bi-list toggle-sidebar-btn"></i>
                </div><!-- End Logo -->

                <nav class="header-nav ms-auto">
                    <ul class="d-flex align-items-center">
                        <!-- Profile dropdown -->
                        <li class="nav-item dropdown pe-3">
                            <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="~/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@CommonVariable.UserName()</span>
                            </a>
                            <!-- Dropdown menu -->
                            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile" aria-labelledby="profileDropdown">
                                <li>
                                    <form asp-controller="User" asp-action="Logout" method="post">
                                        <button type="submit" class="dropdown-item d-flex align-items-center">
                                            <i class="bi bi-box-arrow-right"></i>
                                            <span>Log Out</span>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </li><!-- End Profile Nav -->
                    </ul>
                </nav><!-- End Icons Navigation -->
            </header><!-- End Header -->


    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
       <ul class="sidebar-nav" id="sidebar-nav">
           
           <li class="nav-item">
                <a class="nav-link" asp-controller="User" asp-action="User">
                    <i class="bi bi-person"></i><span>User</span>
                </a>
           </li>
           <!-- End User Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="Product" asp-action="Product">
                    <i class="bi bi-box"></i><span>Product</span>
                </a>
            </li>
            <!-- End Product Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="Customer" asp-action="Customer">
                    <i class="bi bi-people"></i><span>Customer</span>
                </a>
            </li>
            <!-- End Customer Nav -->

            <li class="nav-item">
                 <a class="nav-link" asp-controller="Order" asp-action="Order">
                    <i class="bi bi-receipt"></i><span>Order</span>
                </a>
            </li>
            <!-- End Order Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="OrderDetail" asp-action="OrderDetail">
                    <i class="bi bi-card-list"></i><span>Order Detail</span>
                </a>
            </li>
            <!-- End OrderDetail Nav -->

            <li class="nav-item">
                 <a class="nav-link" asp-controller="Bill" asp-action="Bills">
                    <i class="bi bi-receipt-cutoff"></i><span>Bill</span>
                </a>
            </li>
            <!-- End Bills Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="City" asp-action="Index">
                    <i class="bi bi-house-door"></i><span>City</span>
                </a>
            </li>
            <!-- End City Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="State" asp-action="Index">
                    <i class="bi bi-map"></i>
                    <span>State</span>
                </a>
            </li>
            <!-- End State Nav -->

            <li class="nav-item">
                <a class="nav-link" asp-controller="Country" asp-action="Index">
                    <i class="bi bi-flag"></i><span>Country</span>
                </a>
            </li>
            <!-- End Country Nav -->

            <li class="nav-item">
                 <a class="nav-link" asp-controller="Email" asp-action="Index">
                    <i class="bi bi-envelope"></i><span>Email</span>
                </a>
            </li>
            <!-- End Email Nav -->
        </ul>
    </aside><!-- End Sidebar-->




        <main role="main" class="pb-3">
        @RenderBody()
        </main>


     <!-- ======= Footer ======= -->
                <footer id="footer" class="footer">
                    <div class="copyright">
                        &copy; Copyright <strong><span>Ritesh</span></strong>. All Rights Reserved
                    </div>
                    <div class="credits">
                        <!-- All the links in the footer should remain intact. -->
                        <!-- You can delete the links only if you purchased the pro version. -->
                        <!-- Licensing information: https://bootstrapmade.com/license/ -->
                        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
                        Designed by <a href="https://bootstrapmade.com/">DU</a>
                    </div>
                </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


    <!-- Vendor JS Files -->
    <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/chart.js/chart.umd.js"></script>
    <script src="~/vendor/echarts/echarts.min.js"></script>
    <script src="~/vendor/quill/quill.js"></script>
    <script src="~/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>
    


    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>

    <!-- Include jQuery and Bootstrap JS -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>